language: python
python:
- '3.6'
services:
- docker
env:
- TEST_HOST=TRAVIS
before_install:
- sudo /etc/init.d/mysql stop
-  make prepare_test_env
install:
- pip install codecov
script: make test
after_success:
- make destroy_test_env
- codecov
